In [5]:
import os
import pandas

In [3]:
os.chdir("C:/Users/jonbr/Documents/GitHub/opentrons/j5_files/JAB-j5__20210603140838kG6Y-Synthetic-GFP-IAA/")
os.getcwd()

'C:\\Users\\jonbr\\Documents\\GitHub\\opentrons\\j5_files\\JAB-j5__20210603140838kG6Y-Synthetic-GFP-IAA'

In [6]:
oligos = pandas.read_csv('oligo.csv')
oligos

,ID Number,Name,Length,Tm,Tm (3' only),Cost,Sequence,Sequence (3' only)
0,0,oWL00250_(GFP_plus_link)_forward,42,65.027,54.766,4.2,CACACCAGGTCTCAAATGATGTCTAAAGGTGAAGAATTATTC,ATGTCTAAAGGTGAAGAATTATTC
1,1,oWL00251_(GFP_plus_link)_reverse,34,76.427,65.048,3.4,CACACCAGGTCTCAATCCCACCTGATCCGCCACC,CCCACCTGATCCGCCACC
2,2,oWL00252_(iaa12-prb)_forward,34,68.964,47.768,3.4,CACACCAGGTCTCAGGATGTCTTCTCTTAGTAGA,ATGTCTTCTCTTAGTAGA
3,3,oWL00253_(iaa12-prb)_reverse,36,74.704,61.651,3.6,CACACCAGGTCTCAAGAATCAGTGGTGGTGGTGGTG,TCAGTGGTGGTGGTGGTG

In [7]:
digests = pandas.read_csv('digests.csv')
digests

,ID Number,Sequence Source,Length,Sequence
0,0,pWL34_pIWG_ccdB,4789,TTCTGTCATGTAATTAGTTATGTCACGCTTACATTCACGCCCTCCC...

In [8]:
pcr = pandas.read_csv('pcr.csv')
pcr

,Reaction ID Number,Primary Template,Alternate Template,Forward Oligo ID Number,Forward Oligo Name,Reverse Oligo ID Number,Reverse Oligo Name,Notes,Mean Oligo Tm,Delta Oligo Tm,Mean Oligo Tm (3' Only),Delta Oligo Tm (3'Only),Length,Sequence
0,0,pWL233_pGP4G2_yE,NaN,0,oWL00250_(GFP_plus_link)_forward,1,oWL00251_(GFP_plus_link)_reverse,PCR,70.727,11.40,59.9070,10.282,793,CACACCAGGTCTCAAATGATGTCTAAAGGTGAAGAATTATTCACTG...
1,1,pwl248,NaN,2,oWL00252_(iaa12-prb)_forward,3,oWL00253_(iaa12-prb)_reverse,PCR,71.834,5.74,54.7095,13.883,1180,CACACCAGGTCTCAGGATGTCTTCTCTTAGTAGAGAGCTCGTTTTC...
2,2,pwl277,NaN,2,oWL00252_(iaa12-prb)_forward,3,oWL00253_(iaa12-prb)_reverse,PCR,71.834,5.74,54.7095,13.883,1219,CACACCAGGTCTCAGGATGTCTTCTCTTAGTAGAGAGCTCGTTTTC...
3,3,pwl282,NaN,2,oWL00252_(iaa12-prb)_forward,3,oWL00253_(iaa12-prb)_reverse,PCR,71.834,5.74,54.7095,13.883,1138,CACACCAGGTCTCAGGATGTCTTCTCTTAGTAGAGAGCTCGTTTTC...
4,4,pwl281,NaN,2,oWL00252_(iaa12-prb)_forward,3,oWL00253_(iaa12-prb)_reverse,PCR,71.834,5.74,54.7095,13.883,1177,CACACCAGGTCTCAGGATGTCTTCTCTTAGTAGAGAGCTCGTTTTC...

In [20]:
combinations = pandas.read_csv('combinations.csv')
combinations

,ID Number,Name,Assembly Method,Part(s) Bin 0,Assembly Piece ID Number Bin 0,Part(s) Bin 1,Assembly Piece ID Number Bin 1,Part(s) Bin 2,Assembly Piece ID Number Bin 2
0,0,pmas00001,Golden-gate,(pIWG),0,(GFP_plus_link),1,(iaa12-prb),2
1,1,pmas00002,Golden-gate,(pIWG),0,(GFP_plus_link),1,(iaa12-pdar),3
2,2,pmas00003,Golden-gate,(pIWG),0,(GFP_plus_link),1,(iaa14-prb),4
3,3,pmas00004,Golden-gate,(pIWG),0,(GFP_plus_link),1,(iaa14-pdar),5

In [29]:
e2slot = {}
e2slot['0'] = 'A1'
e2slot['1'] = 'A2'
e2slot['2'] = 'A3'
e2slot['3'] = 'A4'
e2slot['4'] = 'A5'
e2slot['5'] = 'A6'
e2slot['6'] = 'B1'
e2slot['7'] = 'B2'
e2slot['8'] = 'B3'
e2slot['9'] = 'B4'
e2slot['10'] = 'B5'
e2slot['11'] = 'B6'
e2slot['12'] = 'C1'
e2slot['13'] = 'C2'
e2slot['14'] = 'C3'
e2slot['15'] = 'C4'
e2slot['16'] = 'C5'
e2slot['17'] = 'C6'
e2slot['18'] = 'D1'
e2slot['19'] = 'D2'
e2slot['20'] = 'D3'
e2slot['21'] = 'D4'
e2slot['22'] = 'D5'
e2slot['23'] = 'D6'
    
def main():
    f = open('Golden_Gate_instructions.txt','w+')
    f.write('Place the coldtuberack in slot 1. \r\n')
    f.write('put 300uL tips in slot 6 & 9, and 10uL tips in slot 5. \r\n')
    f.write('put in a fresh pcr plate into thermocycler. \r\n')

    f.write('Instructions for setting up the coldtuberack: \r\n')
    for i, row in oligos.iterrows():
        f.write('Put '+oligos.loc[i].at['Name']+' in '+e2slot[str(oligos.loc[i].at['ID Number'])]+'\r\n')
    f.close()
    
    Nextslot = len(oligos["ID Number"])
    
    f = open('Golden_Gate_instructions.txt','a+')
    for i, row in digests.iterrows():
        f.write('Put '+digests.loc[i].at['Sequence Source']+' in '+e2slot[str(Nextslot)]+'\r\n')
        Nextslot = Nextslot+1
    f.close()
    
    Nextslot2 = Nextslot + len(digests["Sequence Source"])-1
    
    f = open('Golden_Gate_instructions.txt','a+')
    for i, row in pcr.iterrows():
        f.write('Put '+pcr.loc[i].at['Primary Template']+' in '+e2slot[str(Nextslot2)]+'\r\n')
        Nextslot2 = Nextslot2+1
    
    f.write('Place empty tube in C4 for the T4/BSA mix \r\n')
    
    f.write('Place T4 ligase in C5 \r\n')

    f.write('Place 100X BSA in C6 \r\n')
    
    f.write('Place T4 buffer in D2 \r\n')
    f.write('Place DPNI in D3 \r\n')
    f.write('Place cutsmart buffer in D4 \r\n')
    f.write('Place BsaI in D5 \r\n')
    f.write('Place Q5 DNA polymerase in D6 \r\n')
    
    
    totaltubes= Nextslot2 + len(pcr['Primary Template'])
    
    f.write('Place 24 well tuberack in slot 2. Add '+str(totaltubes)+' empty 1.5 mL tubes to the rack in the same positions. \r\n')
    
    
    
    numfinaltubes = len(combinations['ID Number'])
    f.write('Place '+str(numfinaltubes)+' tubes in row C of 24 tuberack in slot 2. Start from D6 and go to D'+str(6-numfinaltubes+1)+' \r\n')

    f.close()


    
    
if __name__== "__main__":
    main()